name: commit-bot

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: UPDATE
