name: close-pull-request-bot

on:
  schedule:
    - cron: "0 * * * *"
  pull_request_target:
    types: [opened]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Currently, I do not accept PRs. 🙂"
